site_name: Hexis Documentation
site_description: Universal Hardware Pentesting & Firmware Analysis Framework
repo_url: https://github.com/l3tchupkt/Hexis

theme:
  name: material
  palette:
    primary: deep purple
    accent: cyan

nav:
  - Home: index.md
  - Architecture: architecture.md
  - CLI Guide: cli.md
  - GUI Guide: gui.md
  - Plugins: plugins.md
